export const exhibitStyles = {
  //   root: {
  //     display: "flex",
  //     width: "100%",
  //     minHeight: "100vh",
  //     background: "linear-gradient(135deg, #1a1a2e, #16213e)",
  //     color: "white",
  //     position: "relative",
  //     paddingLeft: "300px",
  //     paddingTop: "70px",
  //     boxSizing: "border-box",
  //     "@media (max-width: 768px)": {
  //       paddingLeft: 0,
  //     },
  //   },
  card: {
    background: "rgb(247, 240, 195)",
    backdropFilter: "blur(12px)",
    borderRadius: "8px",
    height: "400px",
    width: "100%",
    minWidth: "250px",
    margin: "0 auto",
    position: "relative",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    display: "flex",
    flexDirection: "column",
    border: "2px solid rgb(163, 198, 196)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.4), 0 0 0 2px rgb(163, 198, 196)",
    "&:hover": {
      transform: "translateY(-6px)",
      boxShadow: "0 12px 30px rgba(0, 0, 0, 0.6), 0 0 0 2px rgb(133, 92, 117)",
      border: "2px solid rgb(133, 92, 117)",
      "& .MuiCardMedia-root": {
        transform: "scale(1.08)",
      },
    },
  },
  grid: {
    display: "grid",

    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "1.5rem",
    padding: "1rem",
    width: "100%",
    maxWidth: "calc(100vw - 330px)",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
      padding: "0.5rem",
      maxWidth: "100vw",
    },
  },
  mainContent: {
    flexGrow: 1,
    maxWidth: "calc(100vw - 330px)",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    marginLeft: "330px",
    marginTop: "60px",
    "@media (max-width: 768px)": {
      marginLeft: 0,
      marginTop: "2rem",
      width: "100vw",
    },
  },
};
