export const exhibitStyles = {
  mediaContainer: {
    position: "relative",
    height: "180px",
    overflow: "hidden",
    borderRadius: "8px 8px 0 0",
    "&::after": {
      content: '""',
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: "60px",
      background: "linear-gradient(to top, rgba(17, 25, 40, 1), transparent)",
      pointerEvents: "none",
    },
  },
  cardMedia: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  cardContent: {
    padding: "1.2rem",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    background:
      "linear-gradient(180deg, rgb(247, 240, 195, 0.95) 0%, rgb(60, 88, 107, 0.98) 100%)",
  },
  contentWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    flex: "1 1 auto",
  },
  title: {
    fontSize: "1.1rem",
    color: "#855C75",
    fontWeight: 600,
    marginBottom: "0.25rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    minHeight: "2.2em",
    lineHeight: "1.1em",
    "&:hover": {
      overflow: "visible",
      WebkitLineClamp: "unset",
    },
  },
  card: {
    background: "rgb(247, 240, 195)",
    backdropFilter: "blur(12px)",
    borderRadius: "8px",
    height: "400px",
    width: "100%",
    minWidth: "250px",
    margin: "0 auto",
    maxWidth: "100%",
    position: "relative",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    display: "flex",
    flexDirection: "column",
    border: "2px solid rgb(163, 198, 196)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.4), 0 0 0 2px rgb(163, 198, 196)",
    "&:hover": {
      transform: "translateY(-6px)",
      boxShadow: "0 12px 30px rgba(0, 0, 0, 0.6), 0 0 0 2px rgb(60, 88, 107)",
      border: "2px solid rgb(60, 88, 107)",
      "& .MuiCardMedia-root": {
        transform: "scale(1.08)",
      },
    },
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "1.5rem",
    padding: "1rem",
    width: "100%",
    maxWidth: "calc(100vw - 330px)",
    boxSizing: "border-box",
    overflowX: "hidden",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
      padding: "0.5rem",
      maxWidth: "100vw",
    },
  },
  mainContent: {
    flexGrow: 1,
    maxWidth: "calc(100vw - 330px)",
    overflow: "hidden",
    position: "relative",
    width: "100%",
    marginLeft: "315px",
    marginTop: "60px",
    "@media (max-width: 768px)": {
      marginLeft: 0,
      marginTop: "2rem",
      width: "100vw",
    },
  },
};
